# Site settings
title: Ahri - Front End
description: 记录前端成长
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shannuo.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: shannuo
user_description: 成长中的FE，正在寻找前端开发工作。<a href="http://dengshushan.com/resume">简历在此</a>。
email: dengshushan@qq.com
# twitter_username: lorem_ipsum
github_username:  shannuo
# gplus_username:  lorem_ipsum
# disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
